# Site settings
title: sysadm.ru

description: Системное администрирование, Linux, Базы данных, Виртуализация, Cisco
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sysadm.ru" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


gems:
  - jekyll-sitemap
